/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Socket */

#ifndef _Included_Socket
#define _Included_Socket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Socket
 * Method:    socket0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Socket_socket0
  (JNIEnv *, jobject);

/*
 * Class:     Socket
 * Method:    connet0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Socket_connet0
  (JNIEnv *, jobject);

/*
 * Class:     Socket
 * Method:    read0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_Socket_read0
  (JNIEnv *, jobject);

/*
 * Class:     Socket
 * Method:    write0
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_Socket_write0
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
