/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TunTap */

#ifndef _Included_TunTap
#define _Included_TunTap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TunTap
 * Method:    tun_alloc0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TunTap_tun_1alloc0
  (JNIEnv *, jobject);

/*
 * Class:     TunTap
 * Method:    read0
 * Signature: ()I
 */
JNIEXPORT jbyteArray JNICALL Java_TunTap_read0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
