/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Socket */

#ifndef _Included_Socket
#define _Included_Socket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Socket
 * Method:    socket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Socket_socket
  (JNIEnv *, jobject);

/*
 * Class:     Socket
 * Method:    connet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Socket_connet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
